name = "Glade"
author = "Khazoda"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a681cc200986ccd5e1c38e6fb8bdd86bc4de4eefcb414c2196c4e86452acfd2"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.10"]
datapack-folder = "basicweapons_materialpacks/"
no-internal-hashes = ["global_packs/required_resources/*"]
