name = "Glade"
author = "Khazoda"
version = "2.0.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f173225c4e4dc8274c3d94f20060eb0fd4bfc74ff97eb714f01725106a1a6a5"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.11"]
datapack-folder = "basicweapons_materialpacks/"
no-internal-hashes = ["global_packs/required_resources/*"]
