name = "Glade"
author = "Khazoda"
version = "2.0.18"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ff06e02f505bb436bc7fedef3dd684168f46712f35bbaf89d62658f784ecbc2"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.11"]
datapack-folder = "basicweapons_materialpacks/"
no-internal-hashes = ["global_packs/required_resources/*"]
